# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dhiresh Nathwani
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Hardware Hacker - Tech Enthusiast
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://dhiresh.me/" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: DhireshNathwani
#github_username:  BlackrockDigital
#facebook_username: StartBootstrap
instagram_username: dhiresh_nathwani
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
#address_street: 3034 Melrose Place
#address_city: Beverly Hills
#address_state: CA
#address_zip: 90201

# Build settings
markdown: kramdown
